  CREATE TABLE "COURSE" 
   (	"COURSE_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE, 
	"COURSE_TITLE" VARCHAR2(150) NOT NULL ENABLE, 
	"CREDIT" NUMBER(2,1) NOT NULL ENABLE, 
	"COURSE_CODE" VARCHAR2(15), 
	 PRIMARY KEY ("COURSE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DEPARTMENT" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"OFFICE_LOCATION" VARCHAR2(100) NOT NULL ENABLE, 
	"DEPT_CODE" VARCHAR2(10), 
	 PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "FACULTY" 
   (	"FACULTY_ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE, 
	"FACULTY_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESIGNATION" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("FACULTY_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PAYMENT" 
   (	"PAYMENT_ID" NUMBER, 
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE, 
	"PAYMENT_MONTH" NUMBER(2,0) NOT NULL ENABLE, 
	"PAYMENT_YEAR" NUMBER(4,0) NOT NULL ENABLE, 
	"AMOUNT" NUMBER(10,2) NOT NULL ENABLE, 
	"PAYMENT_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"PAYMENT_DATE" DATE, 
	"PAYMENT_METHOD" VARCHAR2(30) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(500), 
	 PRIMARY KEY ("PAYMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SECTION" 
   (	"SECTION_ID" NUMBER, 
	"COURSE_ID" NUMBER NOT NULL ENABLE, 
	"FACULTY_ID" NUMBER NOT NULL ENABLE, 
	"SEMESTER_ID" NUMBER NOT NULL ENABLE, 
	"SECTION_NUMBER" VARCHAR2(10) NOT NULL ENABLE, 
	"ROOM_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("SECTION_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SEMESTER" 
   (	"SEMESTER_ID" NUMBER, 
	"TERM" VARCHAR2(20) NOT NULL ENABLE, 
	"YEAR" NUMBER(4,0) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("SEMESTER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "STUDENT" 
   (	"STUDENT_ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"CGPA" NUMBER(3,2) NOT NULL ENABLE, 
	"CURRENT_SEMESTER" NUMBER(2,0) NOT NULL ENABLE, 
	"COMPLETED_CREDITS" NUMBER(3,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("STUDENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TA_APPLICATION" 
   (	"APPLICATION_ID" NUMBER, 
	"STUDENT_ID" NUMBER NOT NULL ENABLE, 
	"SECTION_ID" NUMBER NOT NULL ENABLE, 
	"FACULTY_ID" NUMBER NOT NULL ENABLE, 
	"APPLICATION_DATE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"REVIEW_DATE" DATE, 
	"REMARKS" VARCHAR2(500), 
	 PRIMARY KEY ("APPLICATION_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TA_ASSIGNMENT" 
   (	"ASSIGNMENT_ID" NUMBER, 
	"STUDENT_ID" NUMBER NOT NULL ENABLE, 
	"FACULTY_ID" NUMBER NOT NULL ENABLE, 
	"SECTION_ID" NUMBER NOT NULL ENABLE, 
	"ASSIGN_DATE" DATE NOT NULL ENABLE, 
	"WEEKLY_HOURS" NUMBER(2,0) NOT NULL ENABLE, 
	"ASSIGNMENT_STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("ASSIGNMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TA_DUTY" 
   (	"DUTY_ID" NUMBER, 
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"ASSIGNED_DATE" DATE NOT NULL ENABLE, 
	"DEADLINE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(500), 
	 PRIMARY KEY ("DUTY_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TA_USERS" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(200) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(200), 
	"ROLE" VARCHAR2(50) DEFAULT 'TA', 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y', 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("USERNAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "WORK_LOG" 
   (	"WORKING_ID" NUMBER, 
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE, 
	"WORK_DATE" DATE NOT NULL ENABLE, 
	"HOURS_WORKED" NUMBER(4,2) NOT NULL ENABLE, 
	"TASK_COMPLETED" VARCHAR2(500) NOT NULL ENABLE, 
	"APPROVED_BY_FACULTY" VARCHAR2(3) NOT NULL ENABLE, 
	 PRIMARY KEY ("WORKING_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "COURSE" ADD CONSTRAINT "FK_COURSE_DEPT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENT" ("DEPARTMENT_ID") ENABLE;

  ALTER TABLE "FACULTY" ADD CONSTRAINT "FK_FACULTY_DEPT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENT" ("DEPARTMENT_ID") ENABLE;
  ALTER TABLE "FACULTY" ADD CONSTRAINT "FK_FACULTY_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "APP_USER" ("USER_ID") ENABLE;

  ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_PAYMENT_ASSIGN" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "TA_ASSIGNMENT" ("ASSIGNMENT_ID") ENABLE;

  ALTER TABLE "SECTION" ADD CONSTRAINT "FK_SECTION_COURSE" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "COURSE" ("COURSE_ID") ENABLE;
  ALTER TABLE "SECTION" ADD CONSTRAINT "FK_SECTION_FACULTY" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "FACULTY" ("FACULTY_ID") ENABLE;
  ALTER TABLE "SECTION" ADD CONSTRAINT "FK_SECTION_SEMESTER" FOREIGN KEY ("SEMESTER_ID")
	  REFERENCES "SEMESTER" ("SEMESTER_ID") ENABLE;

  ALTER TABLE "STUDENT" ADD CONSTRAINT "FK_STUDENT_DEPT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENT" ("DEPARTMENT_ID") ENABLE;
  ALTER TABLE "STUDENT" ADD CONSTRAINT "FK_STUDENT_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "APP_USER" ("USER_ID") ENABLE;

  ALTER TABLE "TA_APPLICATION" ADD CONSTRAINT "FK_TAAPP_FACULTY" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "FACULTY" ("FACULTY_ID") ENABLE;
  ALTER TABLE "TA_APPLICATION" ADD CONSTRAINT "FK_TAAPP_SECTION" FOREIGN KEY ("SECTION_ID")
	  REFERENCES "SECTION" ("SECTION_ID") ENABLE;
  ALTER TABLE "TA_APPLICATION" ADD CONSTRAINT "FK_TAAPP_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE;

  ALTER TABLE "TA_ASSIGNMENT" ADD CONSTRAINT "FK_TAASSIGN_FACULTY" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "FACULTY" ("FACULTY_ID") ENABLE;
  ALTER TABLE "TA_ASSIGNMENT" ADD CONSTRAINT "FK_TAASSIGN_SECTION" FOREIGN KEY ("SECTION_ID")
	  REFERENCES "SECTION" ("SECTION_ID") ENABLE;
  ALTER TABLE "TA_ASSIGNMENT" ADD CONSTRAINT "FK_TAASSIGN_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "STUDENT" ("STUDENT_ID") ENABLE;

  ALTER TABLE "TA_DUTY" ADD CONSTRAINT "FK_TADUTY_ASSIGN" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "TA_ASSIGNMENT" ("ASSIGNMENT_ID") ENABLE;

  ALTER TABLE "WORK_LOG" ADD CONSTRAINT "FK_WORKLOG_ASSIGN" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "TA_ASSIGNMENT" ("ASSIGNMENT_ID") ENABLE;
create or replace FUNCTION TA_APP_AUTH (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
)
RETURN BOOLEAN
IS
    l_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_count
      FROM TA_USERS
     WHERE UPPER(USERNAME) = UPPER(p_username)
       AND PASSWORD_HASH = UPPER(STANDARD_HASH(p_password, 'SHA256'))
       AND IS_ACTIVE = 'Y';

    RETURN l_count > 0;
END;
/
create or replace FUNCTION ta_authenticate ( p_username IN VARCHAR2, p_password IN VARCHAR2 ) RETURN BOOLEAN IS l_count NUMBER; BEGIN SELECT COUNT(*) INTO l_count FROM ta_users WHERE username = p_username AND password_hash = STANDARD_HASH(p_password, 'SHA256') AND is_active = 'Y'; RETURN (l_count > 0); END;
/

















  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CGPAOFSTUDENT" ("STUDENT_ID", "USER_ID", "DEPARTMENT_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE", "CGPA", "CURRENT_SEMESTER", "COMPLETED_CREDITS") AS 
  SELECT "STUDENT_ID","USER_ID","DEPARTMENT_ID","FIRST_NAME","LAST_NAME","EMAIL","PHONE","CGPA","CURRENT_SEMESTER","COMPLETED_CREDITS" FROM STUDENT DETAILS
WHERE CGPA < 3.67;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_FACULTY_WITH_MULTIPLE_TAS" ("FACULTY_NAME", "TA_COUNT") AS 
  SELECT f.faculty_name, COUNT(*) AS ta_count
FROM faculty f
JOIN ta_assignment ta ON ta.faculty_id = f.faculty_id
WHERE ta.assignment_status = 'ACTIVE'
GROUP BY f.faculty_name
HAVING COUNT(*) > 1;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_HOURS_WORKED_PER_TA" ("TA_NAME", "TOTAL_HOURS") AS 
  SELECT s.first_name || ' ' || s.last_name AS ta_name,
       SUM(w.hours_worked) AS total_hours
FROM work_log w
JOIN ta_assignment ta ON ta.assignment_id = w.assignment_id
JOIN student s ON s.student_id = ta.student_id
GROUP BY s.first_name, s.last_name;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_TA_FACULTY_MAPPING" ("TA_NAME", "FACULTY_NAME", "COURSE_TITLE", "SECTION_NUMBER") AS 
  SELECT s.first_name || ' ' || s.last_name AS ta_name,
       f.faculty_name,
       c.course_title,
       sec.section_number
FROM ta_assignment ta
JOIN student s   ON s.student_id  = ta.student_id
JOIN faculty f   ON f.faculty_id  = ta.faculty_id
JOIN section sec ON sec.section_id = ta.section_id
JOIN course c    ON c.course_id   = sec.course_id
WHERE ta.assignment_status = 'ACTIVE';